spring:

  # -------- JPA-MySQL 多数据源配置 --------
  datasource:
    fnclass:
      # MySQL8之后需要指定时区和安全连接方式
      # MySQL数据库-1：基础人员
      jdbc-url: jdbc:mysql://127.0.0.1:3306/49_class_database?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
      password: Admin_1126
      username: adminc
      driver-class-name: com.mysql.cj.jdbc.Driver
    # MySQL数据库-2：基础行政区划
    area:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/area_database?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
      password: Admin_1126
      username: adminc
      driver-class-name: com.mysql.cj.jdbc.Driver
    # MySQL数据库-3：后期生成的中间数据
    base:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/base_database?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
      password: Admin_1126
      username: adminc
      driver-class-name: com.mysql.cj.jdbc.Driver

  # -------- JPA设置 --------
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    database: mysql
    properties:
      format_sql: true

  # -------- Redis 缓存配置 --------
  # Redis
  # Redis配置分为一台服务器上1个redis服务和多个redis服务之分
  # Lettuce的配置是通用的
  redis:
    # springboot 1.5.x版本的默认的Redis客户端是 Jedis实现的；
    # springboot 2.x版本中默认客户端是用 lettuce实现的，使用Netty NIO框架。
    lettuce:
      # 使用连接池必须添加 org.apache.commons:commons-pool2 依赖
      pool:
        # 连接池最大链接数默认值为8
        max-active: 8
        # 连接池最大阻塞时间（使用负值表示没有限制）默认为-1
        max-wait: -1
        # 连接池中的最大空闲连接数 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接数 默认为0
        min-idle: 8

  # 配置Redis0数据库
  # 执行前启动本地服务：rediserver79
  redis0:
    host: 127.0.0.1
    port: 6379
    # 当前使用的Redis数据库索引，默认为0
    database: 0
    # 连接超时时间
    timeout: 30s

  # 配置Redis1数据库
  # 2021年12月14日10:44:16 注释，暂不使用
  # 执行前启动本地服务：rediserver80
  redis1:
    host: 127.0.0.1
    port: 6380
    database: 1
    # 连接超时时间
    timeout: 30s



  # -------- ElasticSearch 数据源配置 --------
  # spring.data.elasticsearch.cluster-name=my-cluster
  # spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300
  # 以上2个配置项已经过时
  elasticsearch:
    rest:
      # WARN
      # Elasticsearch health check failed org.springframework.data.elasticsearch.client.NoReachableHostException:
      # Host 'localhost:9200' not reachable. Cluster state is offline.
      uris: ["http://es.yannises.cn"]
    host-name: es.yannises.cn