

okhttp:
  connectTimeout: 30
  readTimeout: 30
  writeTimeout: 30
  # 连接池中整体的空闲连接的最大数量
  maxIdleConnections: 200
  # 连接空闲时间最多为 300 秒
  keepAliveDuration: 300

# 文件上传服务
file:
  upload:
    # BaseUrl
    serverUrl: http://60.216.119.170:50000/panserver/
    # 图片上传url
    uploadUrl: files/file/directupload
    # 2个参数
    createUser: 66662
    parentId: 66662