# SpringBoot Actuator\u914D\u7F6E
# ----------------------

management:
  endpoints:
    # \u901A\u8FC7HTTP\u66B4\u9732Actuator endpoints
    web:
      exposure:
        include: "*"
        exclude:

    # \u901A\u8FC7JMX\u66B4\u9732Actuator endpoints
    jmx:
      exposure:
        include: "*"
        exclude:
  endpoint:
    health:
      # \u663E\u793A\u5065\u5EB7\u8BE6\u60C5
      show-details: always